/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.Controlador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Casillero;
import modelo.Revista;

/**
 *
 * @author dark1
 */
public class crearRevista extends javax.swing.JDialog {
    private static Casillero casillero;
    /**
     * Creates new form crearPaquete
     */
    public crearRevista(java.awt.Frame parent, boolean modal, Casillero casillero) {
        super(parent, modal);
        this.casillero = casillero;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_id = new javax.swing.JTextField();
        txt_peso = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        txt_remitente = new javax.swing.JTextField();
        lbl_id = new javax.swing.JLabel();
        lbl_peso = new javax.swing.JLabel();
        lbl_descripcion = new javax.swing.JLabel();
        lbl_remitente = new javax.swing.JLabel();
        btn_crearRevista = new javax.swing.JButton();
        lbl_error = new javax.swing.JLabel();
        lbl_tipoRevista = new javax.swing.JLabel();
        lbl_esCatalogo = new javax.swing.JLabel();
        checkB_esCatalogo = new javax.swing.JCheckBox();
        txt_tema = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txt_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcionActionPerformed(evt);
            }
        });

        lbl_id.setText("Id:");

        lbl_peso.setText("Peso:");

        lbl_descripcion.setText("Descripción:");

        lbl_remitente.setText("Remitente:");

        btn_crearRevista.setText("Crear revista");
        btn_crearRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearRevistaActionPerformed(evt);
            }
        });

        lbl_tipoRevista.setText("Tema de la revista:");

        lbl_esCatalogo.setText("Es catálogo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_id)
                                    .addComponent(lbl_peso)
                                    .addComponent(lbl_descripcion)
                                    .addComponent(lbl_remitente)
                                    .addComponent(lbl_tipoRevista)
                                    .addComponent(lbl_esCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_id)
                                            .addComponent(txt_peso)
                                            .addComponent(txt_descripcion)
                                            .addComponent(txt_remitente, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                            .addComponent(txt_tema)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkB_esCatalogo)
                                        .addGap(24, 24, 24)))))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_crearRevista)
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_peso))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_descripcion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_remitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_remitente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tipoRevista)
                    .addComponent(txt_tema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkB_esCatalogo)
                    .addComponent(lbl_esCatalogo))
                .addGap(13, 13, 13)
                .addComponent(lbl_error, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_crearRevista)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcionActionPerformed

    private void btn_crearRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearRevistaActionPerformed
        boolean error = false;
        String mensajeError = "";
        lbl_error.setText("");
        ArrayList<String> listaDatos = new ArrayList<>();
        listaDatos.add(txt_descripcion.getText());
        listaDatos.add(txt_id.getText());
        listaDatos.add(txt_peso.getText());
        listaDatos.add(txt_remitente.getText());
        listaDatos.add(txt_tema.getText());
        
        if (!Controlador.getSingletonInstance().getGestorCliente().validarDatoVacio(listaDatos)) {
            mensajeError += "No se debe dejar espacios en blanco.\n";
            lbl_error.setText(mensajeError);
        }else{
            if (!Controlador.getSingletonInstance().validarDigitosEnteros(txt_id.getText())) {
                mensajeError += "El identificador debe ser un dígito mayor a 0.\n";
                lbl_error.setText(mensajeError);
                error = true;
            }
            if (!Controlador.getSingletonInstance().validarDigitosDobles(txt_peso.getText())) {
                mensajeError += "El peso debe ser un dígito mayor a 0.0.\n";
                lbl_error.setText(mensajeError);
                error = true;
            }
            
            if (!error) {
                Revista revista = Controlador.getSingletonInstance().getGestorEntregable().crearRevista(
                        checkB_esCatalogo.isSelected(), txt_tema.getText(), txt_id.getText(),
                        txt_peso.getText(), txt_descripcion.getText(), txt_remitente.getText());
                
                boolean insertado = Controlador.getSingletonInstance()
                            .getGestorEntregable().buscarEntregableEInsertar(revista, casillero);
                
                if (!insertado) { //Si no lo insertó
                        lbl_error.setText("Ya existe un entregable con el mismo id.");
                }else{
                    JOptionPane.showMessageDialog(this, "Se registró la revista con éxito", "Paquete registrado", JOptionPane.INFORMATION_MESSAGE);
                    casillero.getCliente().aumentarCantidadEntregablesRecibidos();
                    Controlador.getSingletonInstance().getGestorCliente().verificarTipoCliente(casillero.getCliente());
                    this.dispose();
                }
                        
            }
        }
    }//GEN-LAST:event_btn_crearRevistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearRevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearRevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearRevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearRevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                crearRevista dialog = new crearRevista(new javax.swing.JFrame(), true, casillero);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_crearRevista;
    private javax.swing.JCheckBox checkB_esCatalogo;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_esCatalogo;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_peso;
    private javax.swing.JLabel lbl_remitente;
    private javax.swing.JLabel lbl_tipoRevista;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_peso;
    private javax.swing.JTextField txt_remitente;
    private javax.swing.JTextField txt_tema;
    // End of variables declaration//GEN-END:variables
}
