
package vista;

import control.Controlador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Casillero;
import modelo.Sobre;

public class crearSobre extends javax.swing.JDialog {
    private static Casillero casillero;
    public crearSobre(java.awt.Frame parent, boolean modal, Casillero casillero) {
        super(parent, modal);
        this.casillero = casillero;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_id = new javax.swing.JTextField();
        txt_peso = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        txt_remitente = new javax.swing.JTextField();
        lbl_id = new javax.swing.JLabel();
        lbl_peso = new javax.swing.JLabel();
        lbl_descripcion = new javax.swing.JLabel();
        lbl_remitente = new javax.swing.JLabel();
        btn_crearSobre = new javax.swing.JButton();
        lbl_error = new javax.swing.JLabel();
        lbl_tipoSobre = new javax.swing.JLabel();
        cb_tipoSobre = new javax.swing.JComboBox<>();
        lbl_tieneDocumentos = new javax.swing.JLabel();
        checkB_tieneDocumentos = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txt_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcionActionPerformed(evt);
            }
        });

        lbl_id.setText("Id:");

        lbl_peso.setText("Peso:");

        lbl_descripcion.setText("Descripción:");

        lbl_remitente.setText("Remitente:");

        btn_crearSobre.setText("Crear paquete");
        btn_crearSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearSobreActionPerformed(evt);
            }
        });

        lbl_tipoSobre.setText("Tipo de sobre:");

        cb_tipoSobre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aéreo", "Manilla" }));

        lbl_tieneDocumentos.setText("Tiene documentos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_crearSobre)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_id)
                            .addComponent(lbl_peso)
                            .addComponent(lbl_descripcion)
                            .addComponent(lbl_remitente)
                            .addComponent(lbl_tipoSobre)
                            .addComponent(lbl_tieneDocumentos))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_id)
                                    .addComponent(txt_peso)
                                    .addComponent(txt_descripcion)
                                    .addComponent(txt_remitente, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(cb_tipoSobre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkB_tieneDocumentos)
                                .addGap(28, 28, 28)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_peso))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_descripcion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_remitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_remitente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tipoSobre)
                    .addComponent(cb_tipoSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkB_tieneDocumentos)
                    .addComponent(lbl_tieneDocumentos))
                .addGap(18, 18, 18)
                .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_crearSobre)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcionActionPerformed

    private void btn_crearSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearSobreActionPerformed
        boolean error = false;
        String mensajeError = "";
        lbl_error.setText("");
        ArrayList<String> listaDatos = new ArrayList<>();
        listaDatos.add(txt_id.getText());
        listaDatos.add(txt_peso.getText());
        listaDatos.add(txt_descripcion.getText());
        listaDatos.add(txt_remitente.getText());
        
        if(Controlador.getSingletonInstance().getGestorCliente().validarDatoVacio(listaDatos)){
            if (Controlador.getSingletonInstance().validarDigitosEnteros(txt_id.getText())){
                if (Controlador.getSingletonInstance().validarDigitosDobles(txt_peso.getText())){
                    Sobre sobre = Controlador.getSingletonInstance().getGestorEntregable().crearSobre(Integer.parseInt(txt_id.getText()), 
                            Double.parseDouble(txt_peso.getText()), 
                            txt_descripcion.getText(), txt_remitente.getText(),(String)cb_tipoSobre.getSelectedItem(),checkB_tieneDocumentos.isSelected());
                    boolean insertado = Controlador.getSingletonInstance().getGestorEntregable().buscarEntregableEInsertar(sobre, casillero);
                    if (!insertado) { //Si no lo insertó
                        lbl_error.setText("Ya existe un sobre con el mismo id.");
                    }
                    
                    JOptionPane.showMessageDialog(this, "Se registró el sobre con éxito", "Sobre registrado", JOptionPane.INFORMATION_MESSAGE);
                    casillero.getCliente().aumentarCantidadEntregablesRecibidos();
                    Controlador.getSingletonInstance().getGestorCliente().verificarTipoCliente(casillero.getCliente());
                    this.dispose();
                }
                mensajeError = mensajeError  + "El peso debe ser un número.\n";     
            }
            mensajeError = mensajeError  + "El id debe ser un número entero.\n";
        }
            mensajeError = mensajeError + "No se pueden dejar espacios en blanco.\n";    
        
        
    }//GEN-LAST:event_btn_crearSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                crearSobre dialog = new crearSobre(new javax.swing.JFrame(), true, casillero);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_crearSobre;
    private javax.swing.JComboBox<String> cb_tipoSobre;
    private javax.swing.JCheckBox checkB_tieneDocumentos;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_peso;
    private javax.swing.JLabel lbl_remitente;
    private javax.swing.JLabel lbl_tieneDocumentos;
    private javax.swing.JLabel lbl_tipoSobre;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_peso;
    private javax.swing.JTextField txt_remitente;
    // End of variables declaration//GEN-END:variables
}
