/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.Controlador;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.xml.bind.annotation.XmlElement;
import modelo.Cliente;
import modelo.Entregable;
import modelo.Paquete;
import modelo.Revista;
import modelo.Sobre;

/**
 *
 * @author dark1
 */
public class retiroArticulos extends javax.swing.JDialog {
    private static Cliente cliente;
    /**
     * Creates new form retiroArticulos
     */
    DefaultListModel modeloLista;
    
    public retiroArticulos(java.awt.Frame parent, boolean modal, Cliente cliente) {
        super(parent, modal);
        this.cliente = cliente;
        
        
        initComponents();
        modeloLista = new DefaultListModel();
        list_entregables.setModel(modeloLista);
        for (Entregable entregable : cliente.getCasillero().getListaEntregables()) {
            if (!entregable.isEstado()) {
                if (entregable instanceof Revista) {
                    Revista entregableTemporal = (Revista)entregable;
                    modeloLista.addElement("Id: " + entregable.getId() + " -Revista descripción: " + entregableTemporal.getDescripcion());
                }else if (entregable instanceof Paquete) {
                        Paquete entregableTemporal = (Paquete)entregable;
                        modeloLista.addElement("Id: " + entregable.getId() + " -Paquete descripción: " + entregableTemporal.getDescripcion());
                }else{
                    Sobre entregableTemporal = (Sobre)entregable;
                    modeloLista.addElement("Id: " + entregable.getId() + " -Sobre descripción: " + entregableTemporal.getDescripcion());
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_entregables = new javax.swing.JList<>();
        btn_retirar = new javax.swing.JButton();
        btn_calcular = new javax.swing.JButton();
        lbl_montoColones = new javax.swing.JLabel();
        lbl_montoDolares = new javax.swing.JLabel();
        lbl_dolares = new javax.swing.JLabel();
        lbl_colones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        list_entregables.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_entregables);

        btn_retirar.setText("Retirar");

        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        lbl_montoColones.setText("Monto en colones: ");

        lbl_montoDolares.setText("Monto en dólares: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_montoDolares)
                            .addComponent(lbl_montoColones))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_colones, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(lbl_dolares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                        .addComponent(btn_calcular)
                        .addGap(18, 18, 18)
                        .addComponent(btn_retirar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_retirar)
                            .addComponent(btn_calcular))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_montoDolares)
                            .addComponent(lbl_dolares, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_montoColones)
                            .addComponent(lbl_colones, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(15, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        List<String> listaSeleccionados = list_entregables.getSelectedValuesList();
        ArrayList<String> listaIds = new ArrayList<>();
        for (String entregableSeleccionado : listaSeleccionados) {
            String id = "";
            for (int i = 4; i < entregableSeleccionado.length(); i++) {
                char c = entregableSeleccionado.charAt(i);
                if (c != ' ') {
                    id += c;
                }else{
                    listaIds.add(id);
                    break;
                }
            }
        }
        
        ArrayList<Entregable> listaEntregables = Controlador.getSingletonInstance().getGestorEntregable().buscarEntregablesSeleccionados(listaIds, cliente.getCasillero());
        
        
    }//GEN-LAST:event_btn_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(retiroArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(retiroArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(retiroArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(retiroArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                retiroArticulos dialog = new retiroArticulos(new javax.swing.JFrame(), true, cliente);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_retirar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_colones;
    private javax.swing.JLabel lbl_dolares;
    private javax.swing.JLabel lbl_montoColones;
    private javax.swing.JLabel lbl_montoDolares;
    private javax.swing.JList<String> list_entregables;
    // End of variables declaration//GEN-END:variables
}
