/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.Controlador;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.xml.bind.annotation.XmlElement;
import modelo.Cliente;
import modelo.Entregable;
import modelo.IConstants;
import modelo.Paquete;
import modelo.Revista;
import modelo.Sobre;
import modelo.WebService.Cambio;

/**
 *
 * @author dark1
 */
public class retiroArticulos extends javax.swing.JDialog {
    private static Cliente cliente;
    private boolean bandera;
    /**
     * Creates new form retiroArticulos
     */
    DefaultListModel modeloLista;
    
    public retiroArticulos(java.awt.Frame parent, boolean modal, Cliente cliente) {
        super(parent, modal);
        this.cliente = cliente;
        this.bandera = false;

        initComponents();
        Cambio TipoCambio = new Cambio();
        lbl_Compra1.setText("Compra: " + TipoCambio.getCompra());
        lbl_Venta1.setText("Venta: " + TipoCambio.getVenta());
        modeloLista = new DefaultListModel();
        list_entregables.setModel(modeloLista);
        for (Entregable entregable : cliente.getCasillero().getListaEntregables()) {
            double montoDolares = Controlador.getSingletonInstance().getGestorEntregable().calcularMontoDolaresEntregable(entregable);
            double montoColones = Controlador.getSingletonInstance().getGestorEntregable().conversionColones(montoDolares);
            if (!entregable.isEstado()) {
                if (entregable instanceof Revista) {
                    Revista entregableTemporal = (Revista) entregable;
                    modeloLista.addElement("Id: " + entregable.getId() + " | Tipo: Revista | Descripción: " + entregableTemporal.getDescripcion() + " Monto en dólares: " + montoDolares + " Monto en colones: " + String.format("%.2f",montoColones));
                } else if (entregable instanceof Paquete) {
                    Paquete entregableTemporal = (Paquete) entregable;
                    modeloLista.addElement("Id: " + entregable.getId() + " | Tipo: Paquete | Descripción: " + entregableTemporal.getDescripcion() + " Monto en dólares: " + montoDolares + " Monto en colones: " + String.format("%.2f",montoColones));
                } else {
                    Sobre entregableTemporal = (Sobre) entregable;
                    modeloLista.addElement("Id: " + entregable.getId() + " | Tipo: Sobre | Descripción: " + entregableTemporal.getDescripcion() + " Monto en dólares: " + montoDolares + " Monto en colones: " + String.format("%.2f",montoColones));
                }
                this.bandera = true;
            }
        }

        if (!bandera) {
            btn_calcular.setEnabled(false);
            btn_retirar.setEnabled(false);
            JOptionPane.showMessageDialog(this, "No tiene artículos pendientes.", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_entregables = new javax.swing.JList<>();
        lbl_creacionCounter = new javax.swing.JLabel();
        btn_retirar = new rojeru_san.RSButtonRiple();
        btn_calcular = new rojeru_san.RSButtonRiple();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_Compra1 = new javax.swing.JLabel();
        lbl_Venta1 = new javax.swing.JLabel();
        lbl_colones = new javax.swing.JLabel();
        lbl_dolares = new javax.swing.JLabel();
        lbl_montoDolares = new javax.swing.JLabel();
        lbl_montoColones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 112, 192));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        list_entregables.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_entregables);

        lbl_creacionCounter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_creacionCounter.setForeground(new java.awt.Color(0, 112, 192));
        lbl_creacionCounter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_creacionCounter.setText("Crear Paquete");

        btn_retirar.setText("Retirar");
        btn_retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retirarActionPerformed(evt);
            }
        });

        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 112, 192));
        jLabel2.setText("Tipo de Cambio");

        lbl_Compra1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Compra1.setForeground(new java.awt.Color(0, 112, 192));
        lbl_Compra1.setText("Compra:");

        lbl_Venta1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Venta1.setForeground(new java.awt.Color(0, 112, 192));
        lbl_Venta1.setText("Venta:");

        lbl_colones.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_colones.setForeground(new java.awt.Color(0, 112, 192));

        lbl_dolares.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_dolares.setForeground(new java.awt.Color(0, 112, 192));

        lbl_montoDolares.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_montoDolares.setForeground(new java.awt.Color(0, 112, 192));
        lbl_montoDolares.setText("Monto en dólares: ");

        lbl_montoColones.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_montoColones.setForeground(new java.awt.Color(0, 112, 192));
        lbl_montoColones.setText("Monto en colones: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_montoDolares)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_dolares, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_montoColones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_colones, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lbl_Compra1)
                    .addComponent(lbl_Venta1))
                .addGap(64, 64, 64))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_montoDolares)
                    .addComponent(lbl_dolares, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_montoColones)
                    .addComponent(lbl_colones, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Compra1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Venta1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_creacionCounter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_retirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbl_creacionCounter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_retirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
         List<String> listaSeleccionados = list_entregables.getSelectedValuesList();
            if (!listaSeleccionados.isEmpty()) {
                ArrayList<String> listaIds = new ArrayList<>();
                for (String entregableSeleccionado : listaSeleccionados) {
                    String id = "";
                    for (int i = 4; i < entregableSeleccionado.length(); i++) {
                        char c = entregableSeleccionado.charAt(i);
                        if (c != ' ') {
                            id += c;
                        }else{
                            listaIds.add(id);
                            break;
                        }
                    }
                }

                ArrayList<Entregable> listaEntregables = Controlador.getSingletonInstance().getGestorEntregable().buscarEntregablesSeleccionados(listaIds, cliente.getCasillero());
                double montoDolares = Controlador.getSingletonInstance().getGestorEntregable().calcularMontoDolares(listaEntregables);
                montoDolares = Controlador.getSingletonInstance().getGestorEntregable().calcularDescuento(montoDolares, cliente);
                lbl_dolares.setText(String.valueOf(montoDolares));
                double montoColones = Controlador.getSingletonInstance().getGestorEntregable().conversionColones(montoDolares);
                lbl_colones.setText(String.valueOf(String.format("%.2f",montoColones)));
            }else{
                JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un entregable para calcular el monto a pagar.", "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void btn_retirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retirarActionPerformed
               
        Object opcion = JOptionPane.showInputDialog(null, "Seleccione el método de pago", "Elegir tipo de pago",
                JOptionPane.QUESTION_MESSAGE,null,
                IConstants.METODO_PAGO_COMBOBOX, 
                IConstants.METODO_PAGO_COMBOBOX[0]);
        
        Object opcion2 = new Object();
        
        if (opcion != null) {
            if (opcion.toString().equalsIgnoreCase("De contado")) {
                
            } else if (opcion.toString().equalsIgnoreCase("Tarjeta")) {
                opcion2 = JOptionPane.showInputDialog(null, "Seleccione el tipo de tarjeta.", "Elegir tipo de tarjeta",
                JOptionPane.QUESTION_MESSAGE,null,
                IConstants.TIPOS_TARJETA_COMBOBOX, 
                IConstants.TIPOS_TARJETA_COMBOBOX[0]);
                
            }
            if (opcion2 != null) {
                    List<String> listaSeleccionados = list_entregables.getSelectedValuesList();
                    if (!listaSeleccionados.isEmpty()) {
                        ArrayList<String> listaIds = new ArrayList<>();
                        for (String entregableSeleccionado : listaSeleccionados) {
                            String id = "";
                            for (int i = 4; i < entregableSeleccionado.length(); i++) {
                                char c = entregableSeleccionado.charAt(i);
                                if (c != ' ') {
                                    id += c;
                                } else {
                                    listaIds.add(id);
                                    break;
                                }
                            }
                        }

                        ArrayList<Entregable> listaEntregables = Controlador.getSingletonInstance()
                                .getGestorEntregable().buscarEntregablesSeleccionados(listaIds, cliente.getCasillero());
                        Controlador.getSingletonInstance().getGestorEntregable().retirarEntregables(listaEntregables);
                        cliente.decrementarCantidadEntregablesPendientes(listaSeleccionados.size());
                        JOptionPane.showMessageDialog(this, "Se retiraron los entregables con éxito", "Entregables retirados", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un entregable para retirar.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
        }
        
    }//GEN-LAST:event_btn_retirarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(retiroArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(retiroArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(retiroArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(retiroArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                retiroArticulos dialog = new retiroArticulos(new javax.swing.JFrame(), true, cliente);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btn_calcular;
    private rojeru_san.RSButtonRiple btn_retirar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Compra1;
    private javax.swing.JLabel lbl_Venta1;
    private javax.swing.JLabel lbl_colones;
    private javax.swing.JLabel lbl_creacionCounter;
    private javax.swing.JLabel lbl_dolares;
    private javax.swing.JLabel lbl_montoColones;
    private javax.swing.JLabel lbl_montoDolares;
    private javax.swing.JList<String> list_entregables;
    // End of variables declaration//GEN-END:variables
}
